/**
 * Mass Units
 * Comprehensive set of mass measurement units
 */

import { UnitCategory, UnitCategoryId } from '../unit-types';

// Base category definition for mass units
const massCategory: UnitCategory = {
  id: UnitCategoryId.MASS,
  name: 'Mass',
  icon: 'weight',
  description: 'Units for measuring mass or weight',
  baseUnitId: 'kilogram',
  
  // Commonly used units for quick access
  popularUnits: [
    'kilogram',
    'gram',
    'pound',
    'ounce',
    'ton',
  ],
  
  // Organized into subcategories for better navigation
  subcategories: [
    {
      id: 'metric',
      name: 'Metric',
      description: 'International System of Units (SI)',
      units: [
        {
          id: 'kilogram',
          name: 'Kilogram',
          symbol: 'kg',
          pluralName: 'kilograms',
          aliases: ['kilo', 'kilos', 'kilograms'],
          baseUnit: true,
          toBase: value => value,
          fromBase: value => value,
          precision: 3,
        },
        {
          id: 'gram',
          name: 'Gram',
          symbol: 'g',
          pluralName: 'grams',
          aliases: ['grams', 'gramme', 'grammes'],
          conversionFactor: 0.001,
          toBase: value => value * 0.001,
          fromBase: value => value / 0.001,
          precision: 2,
        },
        {
          id: 'milligram',
          name: 'Milligram',
          symbol: 'mg',
          pluralName: 'milligrams',
          aliases: ['milligrams', 'milligramme', 'milligrammes'],
          conversionFactor: 0.000001,
          toBase: value => value * 0.000001,
          fromBase: value => value / 0.000001,
          precision: 2,
        },
        {
          id: 'microgram',
          name: 'Microgram',
          symbol: 'μg',
          pluralName: 'micrograms',
          aliases: ['micrograms', 'mcg'],
          conversionFactor: 0.000000001,
          toBase: value => value * 0.000000001,
          fromBase: value => value / 0.000000001,
          precision: 2,
        },
        {
          id: 'tonne',
          name: 'Tonne',
          symbol: 't',
          pluralName: 'tonnes',
          aliases: ['metric ton', 'metric tons', 'tonnes'],
          conversionFactor: 1000,
          toBase: value => value * 1000,
          fromBase: value => value / 1000,
          precision: 3,
        },
        {
          id: 'quintal',
          name: 'Quintal',
          symbol: 'q',
          pluralName: 'quintals',
          aliases: ['quintals'],
          conversionFactor: 100,
          toBase: value => value * 100,
          fromBase: value => value / 100,
          precision: 2,
        },
      ],
      popularUnits: ['kilogram', 'gram', 'tonne'],
    },
    {
      id: 'imperial',
      name: 'Imperial & US',
      description: 'US and UK measurement systems',
      units: [
        {
          id: 'pound',
          name: 'Pound',
          symbol: 'lb',
          pluralName: 'pounds',
          aliases: ['pounds', 'lbs', 'lb.'],
          conversionFactor: 0.45359237,
          toBase: value => value * 0.45359237,
          fromBase: value => value / 0.45359237,
          relatedUnits: ['kilogram', 'ounce'],
          precision: 2,
        },
        {
          id: 'ounce',
          name: 'Ounce',
          symbol: 'oz',
          pluralName: 'ounces',
          aliases: ['ounces', 'oz.'],
          conversionFactor: 0.028349523125,
          toBase: value => value * 0.028349523125,
          fromBase: value => value / 0.028349523125,
          relatedUnits: ['pound', 'gram'],
          precision: 2,
        },
        {
          id: 'stone',
          name: 'Stone',
          symbol: 'st',
          pluralName: 'stones',
          aliases: ['stones', 'st.'],
          conversionFactor: 6.35029318,
          toBase: value => value * 6.35029318,
          fromBase: value => value / 6.35029318,
          relatedUnits: ['pound', 'kilogram'],
          precision: 2,
        },
        {
          id: 'ton',
          name: 'Ton (US)',
          symbol: 'ton',
          pluralName: 'tons',
          aliases: ['short ton', 'short tons', 'US ton', 'US tons'],
          conversionFactor: 907.18474,
          toBase: value => value * 907.18474,
          fromBase: value => value / 907.18474,
          relatedUnits: ['tonne', 'long_ton'],
          precision: 3,
        },
        {
          id: 'long_ton',
          name: 'Long Ton (UK)',
          symbol: 'long ton',
          pluralName: 'long tons',
          aliases: ['UK ton', 'UK tons', 'imperial ton', 'imperial tons'],
          conversionFactor: 1016.0469088,
          toBase: value => value * 1016.0469088,
          fromBase: value => value / 1016.0469088,
          relatedUnits: ['ton', 'tonne'],
          precision: 3,
        },
        {
          id: 'grain',
          name: 'Grain',
          symbol: 'gr',
          pluralName: 'grains',
          aliases: ['grains', 'gr.'],
          conversionFactor: 0.0000647989,
          toBase: value => value * 0.0000647989,
          fromBase: value => value / 0.0000647989,
          precision: 2,
        },
        {
          id: 'dram',
          name: 'Dram',
          symbol: 'dr',
          pluralName: 'drams',
          aliases: ['drams', 'dr.'],
          conversionFactor: 0.0017718451953125,
          toBase: value => value * 0.0017718451953125,
          fromBase: value => value / 0.0017718451953125,
          precision: 2,
        },
      ],
      popularUnits: ['pound', 'ounce', 'ton'],
    },
    {
      id: 'apothecary',
      name: 'Apothecary',
      description: 'Pharmaceutical measurement system',
      units: [
        {
          id: 'scruple',
          name: 'Scruple',
          symbol: 's ap',
          pluralName: 'scruples',
          aliases: ['scruples', 'apothecary scruple'],
          conversionFactor: 0.00129598,
          toBase: value => value * 0.00129598,
          fromBase: value => value / 0.00129598,
          precision: 3,
        },
        {
          id: 'carat',
          name: 'Carat',
          symbol: 'ct',
          pluralName: 'carats',
          aliases: ['carats', 'karat', 'karats'],
          conversionFactor: 0.0002,
          toBase: value => value * 0.0002,
          fromBase: value => value / 0.0002,
          precision: 3,
        },
      ],
      popularUnits: ['carat'],
    },
    {
      id: 'asian',
      name: 'Asian',
      description: 'Traditional Asian measurement systems',
      units: [
        {
          id: 'jin',
          name: 'Jin',
          symbol: '斤',
          pluralName: 'jin',
          aliases: ['catty', 'catties', 'jin', 'Chinese pound'],
          conversionFactor: 0.5,
          toBase: value => value * 0.5,
          fromBase: value => value / 0.5,
          precision: 2,
        },
        {
          id: 'liang',
          name: 'Liang',
          symbol: '两',
          pluralName: 'liang',
          aliases: ['tael', 'taels', 'liang'],
          conversionFactor: 0.05,
          toBase: value => value * 0.05,
          fromBase: value => value / 0.05,
          precision: 2,
        },
      ],
      popularUnits: ['jin', 'liang'],
    },
    {
      id: 'physics',
      name: 'Physics',
      description: 'Units used in scientific contexts',
      units: [
        {
          id: 'atomic_mass_unit',
          name: 'Atomic Mass Unit',
          symbol: 'u',
          pluralName: 'atomic mass units',
          aliases: ['dalton', 'daltons', 'AMU', 'amu'],
          conversionFactor: 1.66053906660e-27,
          toBase: value => value * 1.66053906660e-27,
          fromBase: value => value / 1.66053906660e-27,
          precision: 6,
        },
        {
          id: 'electron_mass',
          name: 'Electron Mass',
          symbol: 'me',
          pluralName: 'electron masses',
          aliases: ['electron mass', 'mass of electron'],
          conversionFactor: 9.1093837015e-31,
          toBase: value => value * 9.1093837015e-31,
          fromBase: value => value / 9.1093837015e-31,
          precision: 6,
        },
        {
          id: 'planck_mass',
          name: 'Planck Mass',
          symbol: 'mP',
          pluralName: 'planck masses',
          aliases: ['planck mass'],
          conversionFactor: 2.176434e-8,
          toBase: value => value * 2.176434e-8,
          fromBase: value => value / 2.176434e-8,
          precision: 6,
        },
      ],
      popularUnits: ['atomic_mass_unit'],
    }
  ]
};

export default massCategory; 