/**
 * Volume Units
 * Comprehensive set of volume measurement units
 */

import { UnitCategory, UnitCategoryId } from '../unit-types';

// Base category definition for volume units
const volumeCategory: UnitCategory = {
  id: UnitCategoryId.VOLUME,
  name: 'Volume',
  icon: 'beaker',
  description: 'Units for measuring three-dimensional space or capacity',
  baseUnitId: 'cubic_meter',
  
  // Commonly used units for quick access
  popularUnits: [
    'cubic_meter',
    'liter',
    'gallon_us',
    'cubic_foot',
    'milliliter',
  ],
  
  // Organized into subcategories for better navigation
  subcategories: [
    {
      id: 'metric',
      name: 'Metric',
      description: 'International System of Units (SI)',
      units: [
        {
          id: 'cubic_meter',
          name: 'Cubic Meter',
          symbol: 'm³',
          pluralName: 'cubic meters',
          aliases: ['cubic metres', 'cubic meters', 'cu m', 'cbm'],
          baseUnit: true,
          toBase: value => value,
          fromBase: value => value,
          precision: 3,
        },
        {
          id: 'cubic_centimeter',
          name: 'Cubic Centimeter',
          symbol: 'cm³',
          pluralName: 'cubic centimeters',
          aliases: ['cubic centimetres', 'cubic centimeters', 'cc', 'cu cm'],
          conversionFactor: 0.000001,
          toBase: value => value * 0.000001,
          fromBase: value => value / 0.000001,
          precision: 2,
        },
        {
          id: 'cubic_millimeter',
          name: 'Cubic Millimeter',
          symbol: 'mm³',
          pluralName: 'cubic millimeters',
          aliases: ['cubic millimetres', 'cubic millimeters', 'cu mm'],
          conversionFactor: 0.000000001,
          toBase: value => value * 0.000000001,
          fromBase: value => value / 0.000000001,
          precision: 2,
        },
        {
          id: 'liter',
          name: 'Liter',
          symbol: 'L',
          pluralName: 'liters',
          aliases: ['litres', 'liters', 'l'],
          conversionFactor: 0.001,
          toBase: value => value * 0.001,
          fromBase: value => value / 0.001,
          relatedUnits: ['cubic_decimeter', 'gallon_us'],
          precision: 3,
        },
        {
          id: 'milliliter',
          name: 'Milliliter',
          symbol: 'mL',
          pluralName: 'milliliters',
          aliases: ['millilitres', 'milliliters', 'ml'],
          conversionFactor: 0.000001,
          toBase: value => value * 0.000001,
          fromBase: value => value / 0.000001,
          relatedUnits: ['cubic_centimeter'],
          precision: 2,
        },
        {
          id: 'cubic_decimeter',
          name: 'Cubic Decimeter',
          symbol: 'dm³',
          pluralName: 'cubic decimeters',
          aliases: ['cubic decimetres', 'cubic decimeters', 'cu dm'],
          conversionFactor: 0.001,
          toBase: value => value * 0.001,
          fromBase: value => value / 0.001,
          relatedUnits: ['liter'],
          precision: 3,
        },
        {
          id: 'hectoliter',
          name: 'Hectoliter',
          symbol: 'hL',
          pluralName: 'hectoliters',
          aliases: ['hectolitres', 'hectoliters'],
          conversionFactor: 0.1,
          toBase: value => value * 0.1,
          fromBase: value => value / 0.1,
          precision: 3,
        },
        {
          id: 'cubic_kilometer',
          name: 'Cubic Kilometer',
          symbol: 'km³',
          pluralName: 'cubic kilometers',
          aliases: ['cubic kilometres', 'cubic kilometers'],
          conversionFactor: 1000000000,
          toBase: value => value * 1000000000,
          fromBase: value => value / 1000000000,
          precision: 9,
        },
      ],
      popularUnits: ['liter', 'milliliter', 'cubic_meter'],
    },
    {
      id: 'imperial',
      name: 'Imperial & US',
      description: 'US and UK measurement systems',
      units: [
        {
          id: 'gallon_us',
          name: 'Gallon (US)',
          symbol: 'gal',
          pluralName: 'gallons',
          aliases: ['US gallon', 'US gallons', 'gallons', 'gal'],
          conversionFactor: 0.00378541,
          toBase: value => value * 0.00378541,
          fromBase: value => value / 0.00378541,
          relatedUnits: ['liter', 'gallon_uk'],
          precision: 3,
        },
        {
          id: 'gallon_uk',
          name: 'Gallon (UK)',
          symbol: 'gal UK',
          pluralName: 'gallons',
          aliases: ['UK gallon', 'UK gallons', 'imperial gallon', 'imperial gallons'],
          conversionFactor: 0.00454609,
          toBase: value => value * 0.00454609,
          fromBase: value => value / 0.00454609,
          relatedUnits: ['gallon_us'],
          precision: 3,
        },
        {
          id: 'quart_us',
          name: 'Quart (US)',
          symbol: 'qt',
          pluralName: 'quarts',
          aliases: ['US quart', 'US quarts', 'quarts'],
          conversionFactor: 0.000946353,
          toBase: value => value * 0.000946353,
          fromBase: value => value / 0.000946353,
          relatedUnits: ['gallon_us', 'pint_us'],
          precision: 3,
        },
        {
          id: 'pint_us',
          name: 'Pint (US)',
          symbol: 'pt',
          pluralName: 'pints',
          aliases: ['US pint', 'US pints', 'pints'],
          conversionFactor: 0.000473176,
          toBase: value => value * 0.000473176,
          fromBase: value => value / 0.000473176,
          relatedUnits: ['quart_us', 'cup_us'],
          precision: 3,
        },
        {
          id: 'cup_us',
          name: 'Cup (US)',
          symbol: 'cup',
          pluralName: 'cups',
          aliases: ['US cup', 'US cups', 'cups'],
          conversionFactor: 0.000236588,
          toBase: value => value * 0.000236588,
          fromBase: value => value / 0.000236588,
          relatedUnits: ['pint_us', 'fluid_ounce_us'],
          precision: 3,
        },
        {
          id: 'fluid_ounce_us',
          name: 'Fluid Ounce (US)',
          symbol: 'fl oz',
          pluralName: 'fluid ounces',
          aliases: ['US fluid ounce', 'US fluid ounces', 'fluid ounces'],
          conversionFactor: 0.0000295735,
          toBase: value => value * 0.0000295735,
          fromBase: value => value / 0.0000295735,
          relatedUnits: ['cup_us', 'tablespoon_us'],
          precision: 2,
        },
        {
          id: 'tablespoon_us',
          name: 'Tablespoon (US)',
          symbol: 'tbsp',
          pluralName: 'tablespoons',
          aliases: ['US tablespoon', 'US tablespoons', 'tablespoons', 'tbs'],
          conversionFactor: 0.0000147868,
          toBase: value => value * 0.0000147868,
          fromBase: value => value / 0.0000147868,
          relatedUnits: ['fluid_ounce_us', 'teaspoon_us'],
          precision: 2,
        },
        {
          id: 'teaspoon_us',
          name: 'Teaspoon (US)',
          symbol: 'tsp',
          pluralName: 'teaspoons',
          aliases: ['US teaspoon', 'US teaspoons', 'teaspoons'],
          conversionFactor: 0.00000492892,
          toBase: value => value * 0.00000492892,
          fromBase: value => value / 0.00000492892,
          relatedUnits: ['tablespoon_us'],
          precision: 2,
        },
        {
          id: 'cubic_inch',
          name: 'Cubic Inch',
          symbol: 'in³',
          pluralName: 'cubic inches',
          aliases: ['cubic inches', 'cu in'],
          conversionFactor: 0.0000163871,
          toBase: value => value * 0.0000163871,
          fromBase: value => value / 0.0000163871,
          relatedUnits: ['cubic_foot'],
          precision: 3,
        },
        {
          id: 'cubic_foot',
          name: 'Cubic Foot',
          symbol: 'ft³',
          pluralName: 'cubic feet',
          aliases: ['cubic feet', 'cu ft'],
          conversionFactor: 0.0283168,
          toBase: value => value * 0.0283168,
          fromBase: value => value / 0.0283168,
          relatedUnits: ['cubic_inch', 'cubic_yard'],
          precision: 3,
        },
        {
          id: 'cubic_yard',
          name: 'Cubic Yard',
          symbol: 'yd³',
          pluralName: 'cubic yards',
          aliases: ['cubic yards', 'cu yd'],
          conversionFactor: 0.764555,
          toBase: value => value * 0.764555,
          fromBase: value => value / 0.764555,
          relatedUnits: ['cubic_foot'],
          precision: 3,
        },
      ],
      popularUnits: ['gallon_us', 'fluid_ounce_us', 'cubic_foot'],
    },
    {
      id: 'cooking',
      name: 'Cooking',
      description: 'Units commonly used in cooking',
      units: [
        {
          id: 'drop',
          name: 'Drop',
          symbol: 'drop',
          pluralName: 'drops',
          aliases: ['drops'],
          conversionFactor: 0.00000005,
          toBase: value => value * 0.00000005,
          fromBase: value => value / 0.00000005,
          precision: 2,
        },
        {
          id: 'dash',
          name: 'Dash',
          symbol: 'dash',
          pluralName: 'dashes',
          aliases: ['dashes'],
          conversionFactor: 0.0000005,
          toBase: value => value * 0.0000005,
          fromBase: value => value / 0.0000005,
          precision: 2,
        },
        {
          id: 'pinch',
          name: 'Pinch',
          symbol: 'pinch',
          pluralName: 'pinches',
          aliases: ['pinches'],
          conversionFactor: 0.0000003,
          toBase: value => value * 0.0000003,
          fromBase: value => value / 0.0000003,
          precision: 2,
        },
        {
          id: 'cup_metric',
          name: 'Cup (Metric)',
          symbol: 'cup',
          pluralName: 'cups',
          aliases: ['metric cup', 'metric cups'],
          conversionFactor: 0.00025,
          toBase: value => value * 0.00025,
          fromBase: value => value / 0.00025,
          precision: 3,
        },
      ],
      popularUnits: ['cup_metric', 'tablespoon_us', 'teaspoon_us'],
    },
    {
      id: 'oil',
      name: 'Oil Industry',
      description: 'Units used in petroleum industry',
      units: [
        {
          id: 'barrel',
          name: 'Barrel',
          symbol: 'bbl',
          pluralName: 'barrels',
          aliases: ['barrels', 'oil barrel', 'oil barrels'],
          conversionFactor: 0.158987,
          toBase: value => value * 0.158987,
          fromBase: value => value / 0.158987,
          precision: 3,
        },
        {
          id: 'oilton',
          name: 'Oil Ton',
          symbol: 'oilton',
          pluralName: 'oil tons',
          aliases: ['oil tons', 'petroleum ton'],
          conversionFactor: 0.159,
          toBase: value => value * 0.159,
          fromBase: value => value / 0.159,
          precision: 3,
        },
      ],
      popularUnits: ['barrel'],
    }
  ]
};

export default volumeCategory; 